// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products.Models;

namespace Products.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20190614080235_renamepr")]
    partial class renamepr
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Products.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "₽"
                        },
                        new
                        {
                            Id = 2,
                            Name = "$"
                        });
                });

            modelBuilder.Entity("Products.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityL");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityL = "Herzogenaurach",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 2,
                            CityL = "Beaverton",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 3,
                            CityL = "Herzogenaurach",
                            Name = "Puma"
                        });
                });

            modelBuilder.Entity("Products.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Available");

                    b.Property<int>("CurrencyID");

                    b.Property<string>("Description");

                    b.Property<int>("ManufacturerID");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            CurrencyID = 2,
                            Description = "fast&furios",
                            ManufacturerID = 1,
                            Name = "A1",
                            Price = 100
                        },
                        new
                        {
                            Id = 2,
                            Available = false,
                            CurrencyID = 2,
                            Description = "soft",
                            ManufacturerID = 3,
                            Name = "B1",
                            Price = 150
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            CurrencyID = 1,
                            Description = "-",
                            ManufacturerID = 2,
                            Name = "C1",
                            Price = 6000
                        });
                });

            modelBuilder.Entity("Products.Models.Product", b =>
                {
                    b.HasOne("Products.Models.Currency", "Currency")
                        .WithMany("Product")
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Products.Models.Manufacturer", "Manufacturer")
                        .WithMany("Product")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
