// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products.Models;

namespace Products.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20190606062959_fk")]
    partial class fk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Products.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "₽"
                        },
                        new
                        {
                            Id = 2,
                            Name = "$"
                        });
                });

            modelBuilder.Entity("Products.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityL");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Producers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityL = "Herzogenaurach",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 2,
                            CityL = "Beaverton",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 3,
                            CityL = "Herzogenaurach",
                            Name = "Puma"
                        });
                });

            modelBuilder.Entity("Products.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Available");

                    b.Property<int>("CurrId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<int>("ProdId");

                    b.HasKey("Id");

                    b.HasIndex("CurrId");

                    b.HasIndex("ProdId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            CurrId = 2,
                            Description = "fast&furios",
                            Name = "A1",
                            Price = 100,
                            ProdId = 1
                        },
                        new
                        {
                            Id = 2,
                            Available = false,
                            CurrId = 2,
                            Description = "soft",
                            Name = "B1",
                            Price = 150,
                            ProdId = 3
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            CurrId = 1,
                            Description = "-",
                            Name = "C1",
                            Price = 6000,
                            ProdId = 2
                        });
                });

            modelBuilder.Entity("Products.Models.Product", b =>
                {
                    b.HasOne("Products.Models.Currency", "Currency")
                        .WithMany("Product")
                        .HasForeignKey("CurrId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Products.Models.Producer", "Producer")
                        .WithMany("Product")
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
