// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products.Models;

namespace Products.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Products.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Currency_");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "₽"
                        },
                        new
                        {
                            Id = 2,
                            Name = "$"
                        });
                });

            modelBuilder.Entity("Products.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityL");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Producer_");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityL = "Herzogenaurach",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 2,
                            CityL = "Beaverton",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 3,
                            CityL = "Herzogenaurach",
                            Name = "Puma"
                        });
                });

            modelBuilder.Entity("Products.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Available");

                    b.Property<int>("CurId");

                    b.Property<int?>("CurrencyId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("PrId");

                    b.Property<int>("Price");

                    b.Property<int?>("ProducerId");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ProducerId");

                    b.ToTable("Products_");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            CurId = 2,
                            Description = "fast&furios",
                            Name = "A1",
                            PrId = 3,
                            Price = 100
                        },
                        new
                        {
                            Id = 2,
                            Available = false,
                            CurId = 2,
                            Description = "soft",
                            Name = "B1",
                            PrId = 2,
                            Price = 150
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            CurId = 1,
                            Description = "-",
                            Name = "C1",
                            PrId = 1,
                            Price = 6000
                        });
                });

            modelBuilder.Entity("Products.Models.Products", b =>
                {
                    b.HasOne("Products.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("Products.Models.Producer", "Producer")
                        .WithMany()
                        .HasForeignKey("ProducerId");
                });
#pragma warning restore 612, 618
        }
    }
}
